//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="FEL", IsNullable=false)]
public partial class stdTWS {
    
    private string trnEstNumField;
    
    private TiposDocumentos tipTrnCodField;
    
    private string trnNumField;
    
    private string trnFecField;
    
    private Monedas monCodField;
    
    private string trnBenConNITField;
    
    private ReceptorEspecial trnBenConEspecialField;
    
    private bool trnBenConEspecialFieldSpecified;
    
    private string trnExpField;
    
    private string trnExentoField;
    
    private stdTWSTrnFraseTipo trnFraseTipoField;
    
    private bool trnFraseTipoFieldSpecified;
    
    private string trnEscCodField;
    
    private string trnEFACECliCodField;
    
    private string trnEFACECliNomField;
    
    private string trnEFACECliDirField;
    
    private string trnObsField;
    
    private string trnEmailField;
    
    private string trnCampAd01Field;
    
    private string trnCampAd02Field;
    
    private string trnCampAd03Field;
    
    private string trnCampAd04Field;
    
    private string trnCampAd05Field;
    
    private string trnCampAd06Field;
    
    private string trnCampAd07Field;
    
    private string trnCampAd08Field;
    
    private string trnCampAd09Field;
    
    private string trnCampAd10Field;
    
    private string trnCampAd11Field;
    
    private string trnCampAd12Field;
    
    private string trnCampAd13Field;
    
    private string trnCampAd14Field;
    
    private string trnCampAd15Field;
    
    private string trnCampAd16Field;
    
    private string trnCampAd17Field;
    
    private string trnCampAd18Field;
    
    private string trnCampAd19Field;
    
    private string trnCampAd20Field;
    
    private string trnCampAd21Field;
    
    private string trnCampAd22Field;
    
    private string trnCampAd23Field;
    
    private string trnCampAd24Field;
    
    private string trnCampAd25Field;
    
    private string trnCampAd26Field;
    
    private string trnCampAd27Field;
    
    private string trnCampAd28Field;
    
    private string trnCampAd29Field;
    
    private string trnCampAd30Field;
    
    private stdTWSStdTWSstdTWSCItstdTWSDIt[] stdTWSDField;
    
    private stdTWSStdTWSNota stdTWSNotaField;
    
    private stdTWSStdTWSstdTWSCamstdTWSCamIt[] stdTWSCamField;
    
    private stdTWSStdTWSExp stdTWSExpField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string TrnEstNum {
        get {
            return this.trnEstNumField;
        }
        set {
            this.trnEstNumField = value;
        }
    }
    
    /// <remarks/>
    public TiposDocumentos TipTrnCod {
        get {
            return this.tipTrnCodField;
        }
        set {
            this.tipTrnCodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string TrnNum {
        get {
            return this.trnNumField;
        }
        set {
            this.trnNumField = value;
        }
    }
    
    /// <remarks/>
    public string TrnFec {
        get {
            return this.trnFecField;
        }
        set {
            this.trnFecField = value;
        }
    }
    
    /// <remarks/>
    public Monedas MonCod {
        get {
            return this.monCodField;
        }
        set {
            this.monCodField = value;
        }
    }
    
    /// <remarks/>
    public string TrnBenConNIT {
        get {
            return this.trnBenConNITField;
        }
        set {
            this.trnBenConNITField = value;
        }
    }
    
    /// <remarks/>
    public ReceptorEspecial TrnBenConEspecial {
        get {
            return this.trnBenConEspecialField;
        }
        set {
            this.trnBenConEspecialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TrnBenConEspecialSpecified {
        get {
            return this.trnBenConEspecialFieldSpecified;
        }
        set {
            this.trnBenConEspecialFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TrnExp {
        get {
            return this.trnExpField;
        }
        set {
            this.trnExpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TrnExento {
        get {
            return this.trnExentoField;
        }
        set {
            this.trnExentoField = value;
        }
    }
    
    /// <remarks/>
    public stdTWSTrnFraseTipo TrnFraseTipo {
        get {
            return this.trnFraseTipoField;
        }
        set {
            this.trnFraseTipoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TrnFraseTipoSpecified {
        get {
            return this.trnFraseTipoFieldSpecified;
        }
        set {
            this.trnFraseTipoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TrnEscCod {
        get {
            return this.trnEscCodField;
        }
        set {
            this.trnEscCodField = value;
        }
    }
    
    /// <remarks/>
    public string TrnEFACECliCod {
        get {
            return this.trnEFACECliCodField;
        }
        set {
            this.trnEFACECliCodField = value;
        }
    }
    
    /// <remarks/>
    public string TrnEFACECliNom {
        get {
            return this.trnEFACECliNomField;
        }
        set {
            this.trnEFACECliNomField = value;
        }
    }
    
    /// <remarks/>
    public string TrnEFACECliDir {
        get {
            return this.trnEFACECliDirField;
        }
        set {
            this.trnEFACECliDirField = value;
        }
    }
    
    /// <remarks/>
    public string TrnObs {
        get {
            return this.trnObsField;
        }
        set {
            this.trnObsField = value;
        }
    }
    
    /// <remarks/>
    public string TrnEmail {
        get {
            return this.trnEmailField;
        }
        set {
            this.trnEmailField = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd01 {
        get {
            return this.trnCampAd01Field;
        }
        set {
            this.trnCampAd01Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd02 {
        get {
            return this.trnCampAd02Field;
        }
        set {
            this.trnCampAd02Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd03 {
        get {
            return this.trnCampAd03Field;
        }
        set {
            this.trnCampAd03Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd04 {
        get {
            return this.trnCampAd04Field;
        }
        set {
            this.trnCampAd04Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd05 {
        get {
            return this.trnCampAd05Field;
        }
        set {
            this.trnCampAd05Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd06 {
        get {
            return this.trnCampAd06Field;
        }
        set {
            this.trnCampAd06Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd07 {
        get {
            return this.trnCampAd07Field;
        }
        set {
            this.trnCampAd07Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd08 {
        get {
            return this.trnCampAd08Field;
        }
        set {
            this.trnCampAd08Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd09 {
        get {
            return this.trnCampAd09Field;
        }
        set {
            this.trnCampAd09Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd10 {
        get {
            return this.trnCampAd10Field;
        }
        set {
            this.trnCampAd10Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd11 {
        get {
            return this.trnCampAd11Field;
        }
        set {
            this.trnCampAd11Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd12 {
        get {
            return this.trnCampAd12Field;
        }
        set {
            this.trnCampAd12Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd13 {
        get {
            return this.trnCampAd13Field;
        }
        set {
            this.trnCampAd13Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd14 {
        get {
            return this.trnCampAd14Field;
        }
        set {
            this.trnCampAd14Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd15 {
        get {
            return this.trnCampAd15Field;
        }
        set {
            this.trnCampAd15Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd16 {
        get {
            return this.trnCampAd16Field;
        }
        set {
            this.trnCampAd16Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd17 {
        get {
            return this.trnCampAd17Field;
        }
        set {
            this.trnCampAd17Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd18 {
        get {
            return this.trnCampAd18Field;
        }
        set {
            this.trnCampAd18Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd19 {
        get {
            return this.trnCampAd19Field;
        }
        set {
            this.trnCampAd19Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd20 {
        get {
            return this.trnCampAd20Field;
        }
        set {
            this.trnCampAd20Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd21 {
        get {
            return this.trnCampAd21Field;
        }
        set {
            this.trnCampAd21Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd22 {
        get {
            return this.trnCampAd22Field;
        }
        set {
            this.trnCampAd22Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd23 {
        get {
            return this.trnCampAd23Field;
        }
        set {
            this.trnCampAd23Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd24 {
        get {
            return this.trnCampAd24Field;
        }
        set {
            this.trnCampAd24Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd25 {
        get {
            return this.trnCampAd25Field;
        }
        set {
            this.trnCampAd25Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd26 {
        get {
            return this.trnCampAd26Field;
        }
        set {
            this.trnCampAd26Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd27 {
        get {
            return this.trnCampAd27Field;
        }
        set {
            this.trnCampAd27Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd28 {
        get {
            return this.trnCampAd28Field;
        }
        set {
            this.trnCampAd28Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd29 {
        get {
            return this.trnCampAd29Field;
        }
        set {
            this.trnCampAd29Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnCampAd30 {
        get {
            return this.trnCampAd30Field;
        }
        set {
            this.trnCampAd30Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("stdTWS.stdTWSCIt.stdTWSDIt", IsNullable=false)]
    public stdTWSStdTWSstdTWSCItstdTWSDIt[] stdTWSD {
        get {
            return this.stdTWSDField;
        }
        set {
            this.stdTWSDField = value;
        }
    }
    
    /// <remarks/>
    public stdTWSStdTWSNota stdTWSNota {
        get {
            return this.stdTWSNotaField;
        }
        set {
            this.stdTWSNotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("stdTWS.stdTWSCam.stdTWSCamIt", IsNullable=false)]
    public stdTWSStdTWSstdTWSCamstdTWSCamIt[] stdTWSCam {
        get {
            return this.stdTWSCamField;
        }
        set {
            this.stdTWSCamField = value;
        }
    }
    
    /// <remarks/>
    public stdTWSStdTWSExp stdTWSExp {
        get {
            return this.stdTWSExpField;
        }
        set {
            this.stdTWSExpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="FEL")]
public enum TiposDocumentos {
    
    /// <remarks/>
    FACT,
    
    /// <remarks/>
    FCAM,
    
    /// <remarks/>
    FPEQ,
    
    /// <remarks/>
    FCAP,
    
    /// <remarks/>
    FESP,
    
    /// <remarks/>
    NABN,
    
    /// <remarks/>
    RDON,
    
    /// <remarks/>
    RECI,
    
    /// <remarks/>
    NDEB,
    
    /// <remarks/>
    NCRE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="FEL")]
public enum Monedas {
    
    /// <remarks/>
    GTQ,
    
    /// <remarks/>
    USD,
    
    /// <remarks/>
    VES,
    
    /// <remarks/>
    CRC,
    
    /// <remarks/>
    SVC,
    
    /// <remarks/>
    NIO,
    
    /// <remarks/>
    DKK,
    
    /// <remarks/>
    NOK,
    
    /// <remarks/>
    SEK,
    
    /// <remarks/>
    CAD,
    
    /// <remarks/>
    HKD,
    
    /// <remarks/>
    TWD,
    
    /// <remarks/>
    PTE,
    
    /// <remarks/>
    EUR,
    
    /// <remarks/>
    CHF,
    
    /// <remarks/>
    HNL,
    
    /// <remarks/>
    GBP,
    
    /// <remarks/>
    ARS,
    
    /// <remarks/>
    DOP,
    
    /// <remarks/>
    COP,
    
    /// <remarks/>
    MXN,
    
    /// <remarks/>
    BRL,
    
    /// <remarks/>
    MYR,
    
    /// <remarks/>
    INR,
    
    /// <remarks/>
    PKR,
    
    /// <remarks/>
    KPW,
    
    /// <remarks/>
    JPY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="FEL")]
public enum ReceptorEspecial {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
public enum stdTWSTrnFraseTipo {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
public partial class stdTWSStdTWSstdTWSCItstdTWSDIt {
    
    private string trnLiNumField;
    
    private string trnArtCodField;
    
    private string trnArtNomField;
    
    private decimal trnCanField;
    
    private decimal trnVUnField;
    
    private string trnUniMedField;
    
    private decimal trnVDesField;
    
    private stdTWSStdTWSstdTWSCItstdTWSDItTrnArtBienSer trnArtBienSerField;
    
    private stdTWSStdTWSstdTWSCItstdTWSDItTrnArtImpAdiCod trnArtImpAdiCodField;
    
    private string trnArtImpAdiUniGravField;
    
    private float trnArtImpAdiMontoField;
    
    private bool trnArtImpAdiMontoFieldSpecified;
    
    private string trnDetCampAdi01Field;
    
    private string trnDetCampAdi02Field;
    
    private string trnDetCampAdi03Field;
    
    private string trnDetCampAdi04Field;
    
    private string trnDetCampAdi05Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string TrnLiNum {
        get {
            return this.trnLiNumField;
        }
        set {
            this.trnLiNumField = value;
        }
    }
    
    /// <remarks/>
    public string TrnArtCod {
        get {
            return this.trnArtCodField;
        }
        set {
            this.trnArtCodField = value;
        }
    }
    
    /// <remarks/>
    public string TrnArtNom {
        get {
            return this.trnArtNomField;
        }
        set {
            this.trnArtNomField = value;
        }
    }
    
    /// <remarks/>
    public decimal TrnCan {
        get {
            return this.trnCanField;
        }
        set {
            this.trnCanField = value;
        }
    }
    
    /// <remarks/>
    public decimal TrnVUn {
        get {
            return this.trnVUnField;
        }
        set {
            this.trnVUnField = value;
        }
    }
    
    /// <remarks/>
    public string TrnUniMed {
        get {
            return this.trnUniMedField;
        }
        set {
            this.trnUniMedField = value;
        }
    }
    
    /// <remarks/>
    public decimal TrnVDes {
        get {
            return this.trnVDesField;
        }
        set {
            this.trnVDesField = value;
        }
    }
    
    /// <remarks/>
    public stdTWSStdTWSstdTWSCItstdTWSDItTrnArtBienSer TrnArtBienSer {
        get {
            return this.trnArtBienSerField;
        }
        set {
            this.trnArtBienSerField = value;
        }
    }
    
    /// <remarks/>
    public stdTWSStdTWSstdTWSCItstdTWSDItTrnArtImpAdiCod TrnArtImpAdiCod {
        get {
            return this.trnArtImpAdiCodField;
        }
        set {
            this.trnArtImpAdiCodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TrnArtImpAdiUniGrav {
        get {
            return this.trnArtImpAdiUniGravField;
        }
        set {
            this.trnArtImpAdiUniGravField = value;
        }
    }
    
    /// <remarks/>
    public float TrnArtImpAdiMonto {
        get {
            return this.trnArtImpAdiMontoField;
        }
        set {
            this.trnArtImpAdiMontoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TrnArtImpAdiMontoSpecified {
        get {
            return this.trnArtImpAdiMontoFieldSpecified;
        }
        set {
            this.trnArtImpAdiMontoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string TrnDetCampAdi01 {
        get {
            return this.trnDetCampAdi01Field;
        }
        set {
            this.trnDetCampAdi01Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnDetCampAdi02 {
        get {
            return this.trnDetCampAdi02Field;
        }
        set {
            this.trnDetCampAdi02Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnDetCampAdi03 {
        get {
            return this.trnDetCampAdi03Field;
        }
        set {
            this.trnDetCampAdi03Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnDetCampAdi04 {
        get {
            return this.trnDetCampAdi04Field;
        }
        set {
            this.trnDetCampAdi04Field = value;
        }
    }
    
    /// <remarks/>
    public string TrnDetCampAdi05 {
        get {
            return this.trnDetCampAdi05Field;
        }
        set {
            this.trnDetCampAdi05Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
public enum stdTWSStdTWSstdTWSCItstdTWSDItTrnArtBienSer {
    
    /// <remarks/>
    B,
    
    /// <remarks/>
    S,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
public enum stdTWSStdTWSstdTWSCItstdTWSDItTrnArtImpAdiCod {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
public partial class stdTWSStdTWSNota {
    
    private stdTWSStdTWSNotaStdTWSstdTWSNotastdTWSNotaIt stdTWSstdTWSNotastdTWSNotaItField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stdTWS.stdTWSNota.stdTWSNotaIt")]
    public stdTWSStdTWSNotaStdTWSstdTWSNotastdTWSNotaIt stdTWSstdTWSNotastdTWSNotaIt {
        get {
            return this.stdTWSstdTWSNotastdTWSNotaItField;
        }
        set {
            this.stdTWSstdTWSNotastdTWSNotaItField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
public partial class stdTWSStdTWSNotaStdTWSstdTWSNotastdTWSNotaIt {
    
    private stdTWSStdTWSNotaStdTWSstdTWSNotastdTWSNotaItTDFEPRegimenAntiguo tDFEPRegimenAntiguoField;
    
    private string tDFEPAutorizacionField;
    
    private string tDFEPSerieField;
    
    private string tDFEPNumeroField;
    
    private string tDFEPFecEmisionField;
    
    /// <remarks/>
    public stdTWSStdTWSNotaStdTWSstdTWSNotastdTWSNotaItTDFEPRegimenAntiguo TDFEPRegimenAntiguo {
        get {
            return this.tDFEPRegimenAntiguoField;
        }
        set {
            this.tDFEPRegimenAntiguoField = value;
        }
    }
    
    /// <remarks/>
    public string TDFEPAutorizacion {
        get {
            return this.tDFEPAutorizacionField;
        }
        set {
            this.tDFEPAutorizacionField = value;
        }
    }
    
    /// <remarks/>
    public string TDFEPSerie {
        get {
            return this.tDFEPSerieField;
        }
        set {
            this.tDFEPSerieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string TDFEPNumero {
        get {
            return this.tDFEPNumeroField;
        }
        set {
            this.tDFEPNumeroField = value;
        }
    }
    
    /// <remarks/>
    public string TDFEPFecEmision {
        get {
            return this.tDFEPFecEmisionField;
        }
        set {
            this.tDFEPFecEmisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
public enum stdTWSStdTWSNotaStdTWSstdTWSNotastdTWSNotaItTDFEPRegimenAntiguo {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
public partial class stdTWSStdTWSstdTWSCamstdTWSCamIt {
    
    private string trnAbonoNumField;
    
    private string trnAbonoFecVenField;
    
    private float trnAbonoMontoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string TrnAbonoNum {
        get {
            return this.trnAbonoNumField;
        }
        set {
            this.trnAbonoNumField = value;
        }
    }
    
    /// <remarks/>
    public string TrnAbonoFecVen {
        get {
            return this.trnAbonoFecVenField;
        }
        set {
            this.trnAbonoFecVenField = value;
        }
    }
    
    /// <remarks/>
    public float TrnAbonoMonto {
        get {
            return this.trnAbonoMontoField;
        }
        set {
            this.trnAbonoMontoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
public partial class stdTWSStdTWSExp {
    
    private stdTWSStdTWSExpStdTWSstdTWSExpstdTWSExpIt stdTWSstdTWSExpstdTWSExpItField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stdTWS.stdTWSExp.stdTWSExpIt")]
    public stdTWSStdTWSExpStdTWSstdTWSExpstdTWSExpIt stdTWSstdTWSExpstdTWSExpIt {
        get {
            return this.stdTWSstdTWSExpstdTWSExpItField;
        }
        set {
            this.stdTWSstdTWSExpstdTWSExpItField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FEL")]
public partial class stdTWSStdTWSExpStdTWSstdTWSExpstdTWSExpIt {
    
    private string nomConsigODestField;
    
    private string dirConsigODestField;
    
    private string codConsigODestField;
    
    private string otraRefField;
    
    private INCOTERM iNCOTERMField;
    
    private string expNomField;
    
    private string expCodField;
    
    /// <remarks/>
    public string NomConsigODest {
        get {
            return this.nomConsigODestField;
        }
        set {
            this.nomConsigODestField = value;
        }
    }
    
    /// <remarks/>
    public string DirConsigODest {
        get {
            return this.dirConsigODestField;
        }
        set {
            this.dirConsigODestField = value;
        }
    }
    
    /// <remarks/>
    public string CodConsigODest {
        get {
            return this.codConsigODestField;
        }
        set {
            this.codConsigODestField = value;
        }
    }
    
    /// <remarks/>
    public string OtraRef {
        get {
            return this.otraRefField;
        }
        set {
            this.otraRefField = value;
        }
    }
    
    /// <remarks/>
    public INCOTERM INCOTERM {
        get {
            return this.iNCOTERMField;
        }
        set {
            this.iNCOTERMField = value;
        }
    }
    
    /// <remarks/>
    public string ExpNom {
        get {
            return this.expNomField;
        }
        set {
            this.expNomField = value;
        }
    }
    
    /// <remarks/>
    public string ExpCod {
        get {
            return this.expCodField;
        }
        set {
            this.expCodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="FEL")]
public enum INCOTERM {
    
    /// <remarks/>
    EXW,
    
    /// <remarks/>
    FCA,
    
    /// <remarks/>
    FAS,
    
    /// <remarks/>
    FOB,
    
    /// <remarks/>
    CFR,
    
    /// <remarks/>
    CIF,
    
    /// <remarks/>
    CPT,
    
    /// <remarks/>
    CIP,
    
    /// <remarks/>
    DDP,
    
    /// <remarks/>
    DAP,
    
    /// <remarks/>
    DAT,
    
    /// <remarks/>
    ZZZ,
}
